### PR TITLE
refs #000: added a default Drupal-phpqa qa stage template

### PR DESCRIPTION
**Pull request by andypanix**

### CODE REVIEW

**Comment by paolomainardi** [comment]
ciao @andypanix we should instead use templates, you can find some nice examples here: https://medium.com/@rossinigiovanni/gitlab-ci-how-to-reuse-your-yml-code-96a82b3d587e

**Comment by andypanix** [comment]
@paolomainardi  it seems that you cannot use anchors when including templates

```
You can't use YAML anchors across different YAML files sourced by include. You can only refer to anchors in the same file. Instead of YAML anchors, you can use the extends keyword.
```

https://docs.gitlab.com/ce/ci/yaml/README.html#include

We must use the `extends` syntax https://docs.gitlab.com/ce/ci/yaml/README.html#extends

So for example you do not write:

```
phpqa:
  <<: *drupal-phpqa
```

to include the template, but

```
phpqa:
  extends: .drupal-phpqa
```

This is probably the right way to include templates.

**Comment by paolomainardi** [comment]
Thanks @andypanix one thing I would like to remove is the stage field, it is something highly opinionated. You can always bring it back in the job who includes this template.

**Comment by andypanix** [comment]
@paolomainardi removed the stage keyword and added some docs

**Pull request merged**
